version: '3.3'

services:
  #  ubuntu:
  #    image: ubuntu
  #    networks:
  #      - application-network
  #    volumes:
  #      - type: bind
  #        source: ~/bws-paas-queue/incoming
  #        target: /queue/incoming
  #      - type: bind
  #        source: ~/bws-paas-queue/active
  #        target: /queue/active
  #        read_only: false
  #    tty: true
  #    entrypoint: [ "/bin/bash" ]

  scope:
    image: weaveworks/scope:1.13.2
    network_mode: "host"
    pid: "host"
    privileged: true
    labels:
      - "works.weave.role=system"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
    command:
      - "--probe.docker=true"

  nginx:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    networks:
      - paas-network
      - backend-network
    volumes:
      - type: bind
        source: /etc/letsencrypt
        target: /etc/letsencrypt
        read_only: true

  paas-backend:
    container_name: 1-paas-backend
    build: ./paas-backend
    networks:
      - backend-network
    volumes:
      - type: bind
        source: ~/bws-paas-queue/incoming
        target: /queue/incoming
        read_only: false
      - type: volume
        source: socket 
        target: /socket
        read_only: false

  container-control:
    build: ./container-control
    networks:
      - paas-network
    volumes:
      - type: bind
        source: ~/bws-paas-queue/incoming
        target: /queue/incoming
        read_only: false
      - type: bind
        source: ~/bws-paas-queue/active
        target: /queue/active
        read_only: false
      - type: volume
        source: socket 
        target: /socket
        read_only: false
        volume:
          nocopy: true
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
    command: [ "--network=paas-network" ]

networks:
  backend-network:
  paas-network:
    external: true

volumes:
  socket:
