version: '3.3'

services:
  ubuntu:
    image: ubuntu
    networks:
      - application-network
    volumes:
      - type: volume
        source: application-incoming
        target: /queue/incoming
        volume:
          nocopy: true
      - type: volume
        source: application-active
        target: /queue/active
        volume:
          nocopy: true
    tty: true
    entrypoint: [ "/bin/bash" ]

  nginx:
    build: ./nginx
    ports:
      - 8080:80
    networks:
      - application-network

  control-panel-backend:
    container_name: 1-control-panel-backend
    build: ./control-panel-backend
    networks:
      - application-network
    volumes:
      - type: volume
        source: application-incoming
        target: /uploadfiles
        volume:
          nocopy: true

  docker-launcher:
    build: ./docker-launcher
    networks:
      - application-network
    volumes:
      - type: volume
        source: application-incoming
        target: /queue/incoming
        volume:
          nocopy: true
      - type: volume
        source: application-active
        target: /queue/active
        volume:
          nocopy: true
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
    command: [ "--network=application-network" ]

networks:
  application-network:
    external: true

volumes:
  application-incoming:
    external: true

  application-active:
    external: true
